on:
  workflow_dispatch:

jobs:
  ament_lint:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:focal
    strategy:
      fail-fast: false
      matrix:
          linter: [copyright, flake8, mypy, pep257, cpplint, xmllint]
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@master
    - uses: ros-tooling/action-ros-lint@master
      with:
        linter: ${{ matrix.linter }}
        distribution: foxy
        package-name: frl_rosbot_onboard
